deleteForm:
  handler: dist/deleteForm/index.handler
  package:
    # path: "dist/deleteForm/"
    patterns:
      - "dist/deleteForm/**"
      - "!dist/deleteForm/**/*.ts"
      - "!dist/deleteForm/**/*.yml"
  name: delete-form-${self:provider.stage}
  memorySize: 128 # mb
  timeout: 5 # seconds
  events:
    - http:
        path: forms/{formId}
        method: DELETE
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:DeleteItem"
      Resource: !GetAtt FormsTable.Arn
