service: form-builder-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  apiGateway:
    apiKeySourceType: HEADER
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    FORMS_TABLE: ${self:custom.formsTableName}
    USERS_TABLE: ${self:custom.usersTableName}
    USER_POOL_ID: !Ref CognitoUserPool
    USER_POOL_CLIENT_ID: !Ref CognitoUserPoolClient

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline

custom:
  # dynamodb tables
  formsTableName: forms-table-${self:provider.stage}
  usersTableName: users-table-${self:provider.stage}
  # cognito user pool
  userPoolName: user-pool-${self:provider.stage}
  # cognito user pool client
  userPoolClientName: user-pool-client-${self:provider.stage}
  # cognito identity pool
  identityPoolName: identity-pool-${self:provider.stage}

functions:
  - ${file(./src/functions/form/createForm/createForm.yml)}
  - ${file(./src/functions/form/getFormsByOwner/getFormsByOwner.yml)}
  - ${file(./src/functions/form/getForm/getForm.yml)}
  - ${file(./src/functions/form/updateForm/updateForm.yml)}
  - ${file(./src/functions/form/deleteForm/deleteForm.yml)}
  - ${file(./src/functions/auth/confirmSignup/confirmSignup.yml)}
  - ${file(./src/functions/auth/customMessage/customMessage.yml)}
  - ${file(./src/functions/auth/login/login.yml)}
  - ${file(./src/functions/auth/postConfirmation/postConfirmation.yml)}
  - ${file(./src/functions/auth/signup/signup.yml)}

package:
  individually: true
  patterns:
    - "!**/**" # quotes needed

resources:
  - ${file(./src/resources/dynamodb/formsTable.yml)}
  - ${file(./src/resources/dynamodb/usersTable.yml)}
  - ${file(./src/resources/cognito/cognitoUserPool.yml)}
  - ${file(./src/resources/cognito/cognitoUserPoolClient.yml)}
  - ${file(./src/resources/cognito/cognitoIdentityPool.yml)}
  - ${file(./src/resources/cognito/cognitoIdentityPoolRoleAttachment.yml)}
  - ${file(./src/resources/cognito/cognitoAuthRole.yml)}
  - ${file(./src/resources/cognito/cognitoUnauthRole.yml)}
