service: form-builder-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  apiGateway:
    apiKeySourceType: HEADER
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    FORM_BUILDER_DATA_TABLE: ${self:custom.formBuilderDataTableName}
    USER_POOL_ID: !Ref CognitoUserPool
    USER_POOL_CLIENT_ID: !Ref CognitoUserPoolClient
  httpApi:
    shouldStartNameWithService: true
    # disableDefaultEndpoint: true
    cors: true
    authorizers:
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ""
            - - "https://cognito-idp."
              - ${self:provider.region}
              - ".amazonaws.com/"
              - !Ref CognitoUserPool
        audience:
          - !Ref CognitoUserPoolClient

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-api-gateway-throttling
  - serverless-domain-manager
custom:
  # dynamodb table
  formBuilderDataTableName: form-builder-data-${self:provider.stage}
  # cognito user pool
  userPoolName: user-pool-${self:provider.stage}
  # cognito user pool client
  userPoolClientName: user-pool-client-${self:provider.stage}
  # cognito identity pool
  identityPoolName: identity-pool-${self:provider.stage}
  # required by serverless-api-gateway-throttling plugin for apigateway
  apiGatewayThrottling:
    maxRequestsPerSecond: 5
    maxConcurrentRequests: 5
  apiDomain:
    dev: dev-api.vtwinforms.com
    prod: api.vtwinforms.com
  # required by serverless-domain-manger plugin for apigateway
  customDomain:
    http:
      domainName: ${self:custom.apiDomain.${self:provider.stage}}
      basePath: ""
      stage: ${self:provider.stage}
      certificateName: vtwinforms.com
      endpointType: regional
      createRoute53Record: false

functions:
  - ${file(./src/functions/dynamoDbStream/insertItemTrigger/insertItemTrigger.yml)}
  - ${file(./src/functions/dynamoDbStream/deleteItemTrigger/deleteItemTrigger.yml)}
  - ${file(./src/functions/user/getUser/getUser.yml)}
  - ${file(./src/functions/workspace/getWorkspaces/getWorkspaces.yml)}
  - ${file(./src/functions/workspace/createWorkspace/createWorkspace.yml)}
  - ${file(./src/functions/workspace/updateWorkspace/updateWorkspace.yml)}
  - ${file(./src/functions/workspace/deleteWorkspace/deleteWorkspace.yml)}
  - ${file(./src/functions/auth/authenticate/authenticate.yml)}
  - ${file(./src/functions/auth/changePassword/changePassword.yml)}
  - ${file(./src/functions/auth/confirmForgotPassword/confirmForgotPassword.yml)}
  - ${file(./src/functions/auth/confirmSignup/confirmSignup.yml)}
  - ${file(./src/functions/auth/customMessage/customMessage.yml)}
  - ${file(./src/functions/auth/forgotPassword/forgotPassword.yml)}
  - ${file(./src/functions/auth/logout/logout.yml)}
  - ${file(./src/functions/auth/postConfirmation/postConfirmation.yml)}
  - ${file(./src/functions/auth/resendCode/resendCode.yml)}
  - ${file(./src/functions/auth/signup/signup.yml)}

package:
  individually: true
  patterns:
    - "!**/**" # quotes needed

resources:
  Resources:
    FormBuilderDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: pk1
            AttributeType: S
          - AttributeName: sk1
            AttributeType: S
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: pk1
                KeyType: HASH
              - AttributeName: sk1
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.formBuilderDataTableName}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.userPoolName}
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        AutoVerifiedAttributes:
          - email
        DeletionProtection: INACTIVE
        EmailConfiguration:
          EmailSendingAccount: DEVELOPER
          SourceArn: arn:aws:ses:us-west-2:954569320321:identity/vtwinforms.com
          From: vTwinForms <denish@vtwinforms.com>
          ReplyToEmailAddress: denish@vtwinforms.com
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
            TemporaryPasswordValidityDays: 30
        Schema:
          - Name: email
            Required: true
            Mutable: true
        UserAttributeUpdateSettings:
          AttributesRequireVerificationBeforeUpdate:
            - email
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.userPoolClientName}
        UserPoolId:
          Ref: CognitoUserPool
        AccessTokenValidity: 9
        IdTokenValidity: 9
        ExplicitAuthFlows:
          - "ALLOW_USER_PASSWORD_AUTH"
          - "ALLOW_REFRESH_TOKEN_AUTH"
          - "ALLOW_CUSTOM_AUTH"
        GenerateSecret: false
        RefreshTokenValidity: 30
    CognitoIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: ${self:custom.identityPoolName}
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          - ClientId:
              Ref: CognitoUserPoolClient
            ProviderName:
              Fn::GetAtt: [CognitoUserPool, ProviderName]
    CognitoIdentityPoolRoles:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId:
          Ref: CognitoIdentityPool
        Roles:
          authenticated:
            Fn::GetAtt: [CognitoAuthRole, Arn]
          unauthenticated:
            Fn::GetAtt: [CognitoUnauthRole, Arn]
    CognitoAuthRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: appAuthRole
        Path: /
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Federated: "cognito-identity.amazonaws.com"
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud":
                    Ref: CognitoIdentityPool
                "ForAnyValue:StringLike":
                  "cognito-identity.amazonaws.com:amr": authenticated
        Policies:
          - PolicyName: "CognitoAuthorizedPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "mobileanalytics:PutEvents"
                    - "cognito-sync:*"
                    - "cognito-identity:*"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - "execute-api:Invoke"
                  Resource: "*"
    CognitoUnauthRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: appUnauthRole
        Path: /
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Federated: "cognito-identity.amazonaws.com"
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud":
                    Ref: CognitoIdentityPool
                "ForAnyValue:StringLike":
                  "cognito-identity.amazonaws.com:amr": unauthenticated
        Policies:
          - PolicyName: "CognitoUnauthorizedPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "mobileanalytics:PutEvents"
                    - "cognito-sync:*"
                    - "cognito-identity:*"
                  Resource: "*"
