createForm:
  handler: ./dist/createForm/index.handler
  package:
    # path: "dist/createForm/"
    patterns:
      - "dist/createForm/**"
      - "!dist/createForm/**/*.ts"
      - "!dist/createForm/**/*.yml"
  name: create-form-${self:provider.stage}
  memorySize: 128 # mb
  timeout: 5 # seconds
  events:
    - http:
        path: forms
        method: POST
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
      Resource: !GetAtt FormsTable.Arn
